### ISSUE TITLE
Generated JSON Schema does not enforce root element

### ISSUE THREAD

**Issue by david-waltermire-nist** [usnistgov/metaschema#11]
The [toolchains/oscal-m2](https://github.com/usnistgov/metaschema/tree/d2f50966329ecb1eb0177db3686987ab0f7bfd21/toolchains/oscal-m2) implementation does not properly generate a JSON schema.

A current generated schema looks like this:
```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  ... snip ...
  "type": "object",
  "definitions": {
    "parent": {
      ... snip ...
    }
  },
  "properties": {
    "parent": {"$ref": "#/definitions/parent"}
    }
  }
}
```

But it's missing a definition of the required properties for the root object.

The following illustrates the addition of a `"required"` property at the end to fix this.

```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  ... snip ...
  "type": "object",
  "definitions": {
    "parent": {
      ... snip ...
    }
  },
  "properties": {
    "parent": {"$ref": "#/definitions/parent"}
    }
  },
  "required": [ "parent" ]
}
```

Unit tests that illustrate this bug are included in PR #10, which has been integrated into master.

**Comment by wendellpiez** [comment]
This is now working. Additionally, at the top we have

```
"additionalProperties" : false,
"maxProperties" : 1
```

which forces only a single, designated property at the root, and nothing else.
