### ISSUE TITLE
More resilient XML comparison utility for CI/CD process validation

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/metaschema#110]
# User Story:

(If this Issue should be in OSCAL repo let me know)

Currently we validate certain processes such as the data conversions by running a comparison utility over XML (or JSON?) files, showing changes between XML inputs and "the same" data coming back from processing.

At present this utility is sensitive to both changes in whitespace (which are tricky to prevent in a Markup->Markdown->Markup transition) and OSCALisms such as the fact that what goes in as `i`, comes back as `em`.

Testing could be made easier if false hits related to these discrepancies did not occur.

## Goals:

Review functionality of the comparison tool in view of requirements. At time of writing we see both whitespace discrepancies (but see #108) and the casting of `strong/em` and `b/i`.

## Dependencies:

Issues #108 and #109 should be addressed first as they may significantly mitigate this problem.

## Acceptance Criteria

- [ ] All [website](https://pages.nist.gov/metaschema) and readme documentation affected by the changes in this issue have been updated. Changes to the website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by david-waltermire-nist** [comment]
This relates to testing metaschema-based XML and JSON conversion (#51, #53, #109). This work should be done as part of building out better unit testing.

**Comment by aj-stein-nist** [comment]
Per discussion, it does seem like the round-tripping scripts and harness is in the OSCAL repo not the Metaschema repo, [at least according to current `develop`](https://github.com/usnistgov/OSCAL/blob/ba932eda86deaeb94d71b845e089ff4fda43d514/build/ci-cd/validate-content-conversion-round-trips.sh).

The question for me in this issue if closed, or related issues, is this a core feature/property of OSCAL that leverages Metaschema that manages to make it possible or this a feature that is core, guaranteed by Metaschema, and *should* be documented, implemented, and tested in this repo and Metaschema implementations?

**Comment by david-waltermire-nist** [comment]
This relates to the OSCAL [validate-content-conversion-round-trips.sh](https://github.com/usnistgov/OSCAL/blob/main/build/ci-cd/validate-content-conversion-round-trips.sh) script. Any work on round tripping should be done related to OSCAL.
