### ISSUE TITLE
Redesign JSON Schema definition naming scheme for transparency

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/metaschema#112]
# User Story:

The JSON Schemas produced for a metaschema would be greatly improved if their labeling (names on objects) were more transparent: they would be both more legible, and more robust in operation.

Currently we run risks of failure in many JSON Schema processors, because names of definitions reflect any (intentional and useful) overloading of names. The definitions must be distinguishable.

## Goals:

Start by reviewing the present state of identifiers assigned to object definitions in the JSON schema, with attention to the representation of both local and global definitions, sometimes of objects with the same name (`prop` etc.)

Consider a more transparent and robust naming scheme that would support the requirement for uniqueness supporting referential integrity.

Consider also whether an upstream solution might be possible, for example requiring that `@name` on any definition in the Metaschema always be unique (at least within a module), and that `use-name` be used where name reuse is wanted. This would help alleviate the problem.

## Dependencies:

@SilentEsper has work that can serve as useful input, here: https://gist.github.com/SilentEsper/6c79c19fd64efbef22d9d2ba1f9b8c09

Related question (@david-waltermire-nist ) - if grouping names only appear when @in-xml='WITH_WRAPPER' (not super-common), is there any reason grouping names could not go `snake_syntax` or `camelSyntax`?

Unit tests!

## Acceptance Criteria

- [ ] All [website](https://pages.nist.gov/metaschema) and readme documentation affected by the changes in this issue have been updated. Changes to the website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.
- [ ] Unit tests have been updated as appropriate

**Comment by wendellpiez** [comment]
@david-waltermire-nist I think we can do this together with #84 along lines we were discussing yesterday. Indeed doing #84 nicely also gives us leverage over this problem. I suggest I make a new branch for both these Issues in one PR?

**Comment by wendellpiez** [comment]
**Update Jan 14**

I have this sketched out in my head, and propose I work in the same branch as PR #111 - so that remains in draft.

critical components:
-[ ] alignment with JSON community on design
-[ ] unit tests- both Metaschema composition, and JSON Schema generation

NB - because Metaschema composition happens upstream of everything else, the entire stack must be tested (and adjusted) after that phase is complete. This includes schema generators, content converter generators, docs etc.

**Comment by wendellpiez** [comment]
Superseding PR #111, I have WIP in a branch in my repository, with JSON Schema definition names now expanded.

It shows however more issues with AJV even after the naming is corrected for: we are using JSON Schema formats that must be configured for as described in https://ajv.js.org/docs/validation.html#formats 

@david-waltermire-nist please let's confer.

**Comment by wendellpiez** [comment]
Okay we now have an updated JSON Schema generator in a branch in my repo.

This also addresses #84 (qv).

If we set up integration branches in this  (metaschema) repo and the OSCAL repo, we can push this up and through and take a look.

We can also do more testing and validation.

**Comment by wendellpiez** [comment]
This Issue is closable when #115 is accepted.

**Comment by david-waltermire-nist** [comment]
Resolved by PR #116.
