### ISSUE TITLE
Define function (library) for OSCAL document set(s)

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/metaschema#114]
# User Story:

OSCAL documents are typically not standalone; profiles make reference to catalogs and depend on them for resolution; SSPs make reference to profiles, etc.

It is likely that in the field, these references and de-references will be actively managed, including caching results of profile resolution etc.; but the definitions of how they interoperate must still be externalized in some way for clarity and consistency; we also need to be able to perform validation-oriented queries across these document boundaries. In the extreme case, the network of documents relating to one another (through import chains etc.) will be a directed graph.

We can describe this graph in a function library that can expose these documents (for example, imported catalogs from a processor operating on a profile) and make them available for processing. One set of functions might retrieve documents; another might serve to provide with runtime validations.

## Goals:

* Break this problem up into bite-size pieces (e.g: imported catalogs from profiles both one-step and recursively)
* Define example use cases with unit tests
* Model function(s)
* Demonstrate deployment in Metatron or other Metaschema validation support pipeline

## Dependencies:

As an experiment to demonstrate feasibility and provide baseline functionality, no dependencies.

However since it is not useful until Metaschema Metapath (constraints definition and enforcement) is deployed, we can wait for that (#45 and related).

## Acceptance Criteria

- [ ] All [website](https://pages.nist.gov/metaschema) and readme documentation affected by the changes in this issue have been updated. Changes to the website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by david-waltermire-nist** [comment]
This is an OSCAL issue and not related to this repo.
