### ISSUE TITLE
Inline definitions in metaschema are not getting xs:annotation (docs) in XSD

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/metaschema#121]
# Describe the bug

XSD supports `xs:annotation` for providing inline documentation on its declarations to tools. This is useful.

Currently it is being provided from metaschema sources for global definitions in an XSD (resulting from metaschema processing), but not inline (local) definitions. (This is easy to see in any generated XSD that has any definitions inline.)

Consequently, these points of documentation are missing from applications that might have been able to show them.

**Comment by wendellpiez** [comment]
This was misdiagnosed: the lapse was not in handling inline definitions, but field defined as `markup-line` or `markup-multiline`.

The omission is remedied in the (working) branch behind PR #124.

**Comment by david-waltermire-nist** [comment]
Addressed by PR #121.
