### ISSUE TITLE
(small) Normalize formal names to title case / Normalize Formal Names to Title Case

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/metaschema#123]
# Describe the bug

Contributors to OSCAL metaschemas have not always exercised editorial consistency in documentation. One area of inconsistency is formal names ("Property" for `prop` etc.), some of which use title case (**Control Implementation**) and others, sentence case (**Role identifier**).

In discussion we decided on title case.

# Who is the bug affecting?

Especially sensitive people who are affected negatively by this inconsistency. (@wendellpiez)

# What is affected by this bug?

Any downstream tooling that takes advantage of schema documentation is likely to display formal names.

# Expected behavior (i.e. solution)

Let's normalize these.

**Comment by david-waltermire-nist** [comment]
@wendellpiez Yes. We should add this to the Metaschema schematron to address this issue.

**Comment by wendellpiez** [comment]
This is now an OSCAL issue.

For another day: determine whether and where Metaschema should support "editorial" Schematron.
