### ISSUE TITLE
XML and JSON Schema docs pages - reorganize page architecture

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/metaschema#128]
# User Story:

Currently both the XML and JSON Schema docs pages have an organization reflecting that of the (composed) metaschema for the model, not for the expressed model itself (XML or JSON).

This leads to much weirdness such as a JSON user not being able to look up a 'task' object because it is not called 'task' (it is an anonymous object member of an array called ('actions' - who knew?), or much confusion around `part` (or is it `parts`?) since there are at least two kinds of parts (so far) that sometimes appear in the same model.

Instead of following the metaschema source (whose organization means nothing to the user), the XML page should be indexed and laid out by element, and the JSON page should be indexed and laid out by name and/or grouping name, whichever appears. This means listing things by their appearance (names in use including applicable `use-name`) and then sublisting by the *apparent* contexts in which those names are used for different things.

Such an organization would also make a clean linking target from the model maps pages, enabling us to resolve Issues #91, #94 and #104.

## Goals:

Redesign page layout of both XML and JSON Schema docs for usability, navigability and readability. See #104, but focus first on page organization and ToC/findability.

## Dependencies:

Work in progress is available on the grouping logic as it would apply to the JSON Schema documentation. It already shows promising results.

## Acceptance Criteria

- [ ] All [website](https://pages.nist.gov/metaschema) and readme documentation affected by the changes in this issue have been updated. Changes to the website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

{The items above are general acceptance criteria for all User Stories. Please describe anything else that must be completed for this issue to be considered resolved.}

**Comment by wendellpiez** [comment]
usnistgov/OSCAL#872 is also about this.

**Comment by david-waltermire-nist** [comment]
This work was completed in PRs #147, #148, and #152.
