### ISSUE TITLE
Build out Github repository templates

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/metaschema#14]
This repository has no templates yet for Issues (bugs, feature requests etc.), or labels, projects or milestones.

The latter, we can make as we go, but templates would be good to have. They can be ported from the OSCAL repo or made fresh, whichever gets us better templates.

**Comment by david-waltermire-nist** [comment]
This was done two years ago in a [previous commit](https://github.com/usnistgov/metaschema/commit/8658f63825f55807403ccfdc6e69a19856c73d4d).
