### ISSUE TITLE
Document the Metaschema (phase 1)

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/metaschema#16]
For the Metaschema repo to go public, some minimal documentation is a prerequisite. @david-waltermire-nist has started on this and has work in a branch in his repository.

This includes readme files as well as its Hugo site.

Work items for this issue:

- [x] Assess current state of site documentation and needs
- [x] Address the gap, including strategy for moving towards a formal specification for Metaschema (syntax and semantics)
- [ ] Capture issues for further work
- [x] Integrate into CI/CD
- [x] Post and accept PR
- [x] Make site and repository public
- [ ] Update metaschema pages in the [OSCAL repository](https://github.com/usnistgov/OSCAL)

**Comment by david-waltermire-nist** [comment]
No clearly identified additional work to do on this issue. Closing.
