### ISSUE TITLE
Enable Production of JSON Schemas with References by Path

### ISSUE THREAD

**Issue by rgauss** [usnistgov/metaschema#160]
# User Story:

As a Metaschema consumer via OSCAL JSON schemas, I want the resulting `$ref` values in those schemas to be by path rather than `$id`.

## Goals:

We would like to be able to reference OSCAL JSON schemas directly in OpenAPI specifications.  However, reference by `$id` rather than path [seems to only be supported in OpenAPI v3.1](https://spec.openapis.org/oas/v3.1.0#relative-references-in-uris) (and [Swagger UI hasn't caught up to that yet](https://github.com/swagger-api/swagger-ui/issues/5891)).

You should be able to see an example of the issue we're encountering through an example which uses a [simple example gist OpenAPI file](https://gist.github.com/rgauss/4cdea191fa672c2b46d8dc54b1323aef):

1. Open [Swagger editor with the example OpenAPI spec](https://editor.swagger.io/?url=https://gist.githubusercontent.com/rgauss/4cdea191fa672c2b46d8dc54b1323aef/raw/8418d1cb7be77fec098a0f37ed39ce6fe57cfe76/oscal-schema-testing-openapi.yaml)
2. Click on OSCALCatalog under Schemas
3. You'll see several errors about not being able to resolve references

## Dependencies:

Relates to https://github.com/usnistgov/OSCAL/issues/933

## Acceptance Criteria

- [ ] All [website](https://pages.nist.gov/metaschema) and readme documentation affected by the changes in this issue have been updated. Changes to the website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

{The items above are general acceptance criteria for all User Stories. Please describe anything else that must be completed for this issue to be considered resolved.}

**Comment by rgauss** [comment]
Here's an [example of what the result might look like](https://github.com/usnistgov/OSCAL/compare/main...EasyDynamics:json-schema-ref-by-path) (and works with Swagger UI).

**Comment by david-waltermire-nist** [comment]
This appears to have been fixed already. See usnistgov/OSCAL#948.
