### ISSUE TITLE
Support glob-matching syntax on a metaschema-based constraint?

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/metaschema#161]
# User Story:

The Metaschema constraints model includes a `matches` constraint with a `@regex`. The implementation of the regex uses XPath regex.

One consideration is matching glob syntax, instead of or in addition to regex.

There is an XSLT glob-syntax-matching implementation in the profile resolution stack. It could be adapted.

## Goals:

Extend capability and usefulness of `matches` constraint across platforms without a common regex syntax.

## Dependencies:

- Establish whether use cases warrant this development
- Confirm stable implementation of `matches[@regex]`

## Acceptance Criteria

- [ ] All [website](https://pages.nist.gov/metaschema) and readme documentation affected by the changes in this issue have been updated. Changes to the website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

{The items above are general acceptance criteria for all User Stories. Please describe anything else that must be completed for this issue to be considered resolved.}

**Comment by david-waltermire-nist** [comment]
Need to define the current use of regex in constraints specifications. We need more than glob. Need to settle on a commonly supported regex syntax.
