### ISSUE TITLE
Streamline and better test Metaschema pipelines

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/metaschema#163]
# User Story:

Metaschema pipelines starting with composition could be streamlined and tested out more comprehensively.

They should be clean with respect to

1. Namespace handling throughout
1. Comments, both inline and initial
1. Emitted outputs including at waypoints
1. Clearly usable and adaptable runtimes for maintenance and testing

## Goals:

Easier maintenance of metaschema-based production over the long term.

## Dependencies:

None. Specifically, this Issue should focus on the current implementations despite (because of) possible migration of metaschema infrastructure runtimes to different platforms (node JS, XProc 3 etc).

## Acceptance Criteria

- [ ] All [website](https://pages.nist.gov/metaschema) and readme documentation affected by the changes in this issue have been updated. Changes to the website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by wendellpiez** [comment]
Work is now happening in a (misnamed) feature/debug branch here: https://github.com/wendellpiez/metaschema/tree/issue196-definition-pruning-enhancement

See also #199.

This Issue needs to be rewritten with achievable goals, probably split.

**Comment by wendellpiez** [comment]
This is an aspirational Issue. Close or move to XSLT M4 stack. Also depends on unit testing.

**Comment by david-waltermire-nist** [comment]
We need to refocus and prioritize what work needs to be done on the XSLT implementation. We should close this issue in favor of new issues that focus on specification future development actions that need to be taken.
