### ISSUE TITLE
Compiling stylesheet fails: unknown accumulator Q{}definition-count 

### ISSUE THREAD

**Issue by avdouglas-nist** [usnistgov/metaschema#180]
While compiling a stylesheet, used in the schema and converter generation, to a .SEF file, received the following error message: 

Failed to compile stylesheet: Static error in XPath on line 38 in compose/metaschema-prune-unused-definitions.xsl {accumulator-after('definition-count')}: Unknown accumulator Q{}definition-count
Error Q{http://www.w3.org/2005/xqt-errors}XTDE3340 at xpath.xsl#963
    Failed to compile stylesheet:
Error Q{http://www.w3.org/2005/xqt-errors}XTDE3340 at xpath.xsl#963
    Static error in XPath on line 38 in compose/metaschema-prune-unused-definitions.xsl {accumulator-after('definition-count')}: Unknown accumulator Q{}definition-count

This could be a Saxon JS bug as well. The traceback reports an error in an accumulator. 

This could possibly affect the transformation process to schemas and converters.

This occurs when the following command is executed:  "xslt3 -t -xsl:metaschema-prune-unused-definitions.xsl -export:metaschema-prune-unused-definitions.sef.json -nogo"

The stylesheet being compiled is located here: https://github.com/usnistgov/metaschema/blob/54d1d8d24edb0f07fe0e8effd5ea476e890ecdb7/toolchains/xslt-M4/compose/metaschema-prune-unused-definitions.xsl

**Comment by wendellpiez** [comment]
The error message is interesting, because it suggests the problem could be dynamic context - how to determine whether an accumulator is 'applicable' or not.

Making sure the runtime context is set correctly for SaxonJS, inside the pipeline, is tricky and could be a problem here. (Indeed it has to be right for all kinds of things to happen.) But this is a compile time error. Suggest reducing to a test case with a simple accumulator we could use to test.

**Comment by aj-stein-nist** [comment]
> The error message is interesting, because it suggests the problem could be dynamic context - how to determine whether an accumulator is 'applicable' or not.

Cool, I will try to move this forward and get my the oscal-cli-nodejs environment on my laptop with @avdouglas-nist early next week and look into what's going on with Saxon (Java) versus SaxonJS.

Does that sound like a good game plan?

**Comment by aj-stein-nist** [comment]
Repo code created here:

https://github.com/aj-stein-nist/issue180example

Waiting for Saxonica to endorse my registration so I can file a bug to ask if the Saxon HE (Java) or SaxonJS implementation is correct in this regard, and which one in fact has the bug.

**Comment by wendellpiez** [comment]
On the ticket above, Mike Kay (Saxonica lead) suggests refactoring the code to use either `xsl:iterate`, or an XPath `fold-left()` -based operation, to achieve the map building in this XSLT. This is worth trying. This would also be an opportunity for us to look together at the guts of Metaschema composition.

**Comment by wendellpiez** [comment]
[metaschema-prune-unused-definitions4.zip](https://github.com/usnistgov/metaschema/files/8344701/metaschema-prune-unused-definitions4.zip)

@aj-stein-nist please try the XSLT in the zip for comparison. Looking at it next to your latest might be instructive.

Also I realized why *all* versions are so much faster than the version they replaced. They don't do the same thing exactly. The current design permits potential leakage of definitions that are never used, is all -- it counts a definition as "used" if it is referenced even by something itself never used. @david-waltermire-nist are currently discussing how to fix this. Comparing with an earlier (pre-refactoring) version of this XSLT may be in order. The bug might actually be inoperative over our schemas (we don't know till we look) which would help account for why we hadn't noticed.

**Comment by aj-stein-nist** [comment]
> [metaschema-prune-unused-definitions4.zip](https://github.com/usnistgov/metaschema/files/8344701/metaschema-prune-unused-definitions4.zip)
> 
> @aj-stein-nist please try the XSLT in the zip for comparison. Looking at it next to your latest might be instructive.
> 
> Also I realized why _all_ versions are so much faster than the version they replaced. They don't do the same thing exactly. The current design permits potential leakage of definitions that are never used, is all -- it counts a definition as "used" if it is referenced even by something itself never used. @david-waltermire-nist are currently discussing how to fix this. Comparing with an earlier (pre-refactoring) version of this XSLT may be in order. The bug might actually be inoperative over our schemas (we don't know till we look) which would help account for why we hadn't noticed.

So this updated approach does not fix that higher-level issue around walking the tree to properly "counts a definition as 'used' if it is referenced even by something itself never used" and we, even with this recommended code, we need to do some `git` bisecting to confirm we can validate how the code before and after this change?

**Comment by wendellpiez** [comment]
We now have code to address this bug, which will be posted with a PR addressing #198. This can be closed when it is closed.
