### ISSUE TITLE
Roll back `token` datatype to avoid problematic character references

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/metaschema#181]
# Describe the bug

As reported in the OSCAL repo https://github.com/usnistgov/OSCAL/issues/1127 a regular expression deployed in the schemas on the **token** datatype definition is breaking in certain tools.

Testing suggests that it is the numeric character escaping (entity syntax) in the expression `[\i-[:&#x10000;-&#xeffff;]][\c-[:&#x10000;-&#xeffff;]]*` that the tool is not able to handle.

But further testing shows that these character exclusions have no apparent effect on the regex - which suggests we should roll them back.

If the XML-regex syntax here for NCName `[\i-[:]][\c-[:]]*` is too XMLy, an alternative could be `[\w-[:\d]]\w*`.

In any case the correction must be made in Metaschema back end, to propagate to into generated schemas.

This is *not* a backward-compatibility breaking change.

# Who is the bug affecting?

Any user of tools that choke on the regex as given.

# What is affected by this bug?

Can't validate an OSCAL instance with an appropriate XSD.

# When does this occur?

Anytime with the tool in question (C# processor under .NET).

As it happens, the oXygen XML Editor's XML Schema Regular Expression builder also does not support entity syntax, and shows the same error.

# Expected behavior (i.e. solution)

The token datatype should be validated appropriately (against NCName constraints).

**Comment by aj-stein-nist** [comment]
Thanks for adding this @wendellpiez, so are you working on this moving forward or should I learn the dark arts of these regex patterns? :-)

**Comment by wendellpiez** [comment]
@david-waltermire-nist with AJ's help we have managed to demonstrate:

* The tool in question does appear to have issues dealing with Unicode ranges, or certain Unicode ranges, that other tools are okay with - possible bug there
* Nonetheless the exclusion of the characters the causes the regex to break, is superfluous and can be removed without effect, as the excluded characters (despite my earlier research) do not appear to be in the character sets to begin with.

(It turns out a test for this is easy: just try and make an XSD definition for an element named `A&#x10000;`.)

So I think the solution here (on the XML side) is to roll back the definition to `[\i-[:]][\c-[:]]*` (no-colon name without exclusions).

Issue #182 *might* give us a reason to do otherwise, but it could also be orthogonal.

**Comment by aj-stein-nist** [comment]
Yeah I hope that helped. I mothballed the project for now but we can always revive and add more tests. I integrated .NET code with GitHub Actions on a Windows runner so we can further test issues with this particular XML engine in the .NET `System.Xml` namespace (since that is different from MSXML, we dodged that bullet 😰).

Let me know if I can be of more help.

**Comment by wendellpiez** [comment]
Now emitting functional XSDs with the new datatype mappings.

Pruning the result XSD so it does not contain unused simpleType definitions is a bit difficult when their definitions are chained, but we are managing some of it at least.

JSON Schema production also looks okay wrt datatypes in this branch.
