### ISSUE TITLE
Correct handling of allowed-values in Metaschema

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/metaschema#19]
# Describe the bug

Metaschema syntax permits a user to specify allowed values (`allowed-values`) for flags and fields. These can be either inclusive (`allow-other='yes'`) or exclusive of values not specified.

These should work for both global declarations (`define-flag`, `define-field`) and local declarations (within the context of `model`). Additionally, when local references are made to global declarations (`field` or `flag` with `@ref` not `@name`), locally declared values need to combine with or override values declared globally.

Exactly how this should work has not actually been fully specified. ("Combine with *or* override.")

And in any case, the functionality is not working, and needs to be unit tested and traced through documentation.

# Who is the bug affecting?

Anyone trying to use a schema made from a metaschema that exercises this feature. Anyone relying on the generated documentation.

# Course of action

1. [ ] Clarify the intended semantics
1. [ ] Mock them up in unit tests
1. Test and refine functionality until tests pass (XSD and JSON schema production)
   - [ ] Add support to XSLT tooling
   - [ ] Add support to Java tooling
1. [ ] Confirm that allowed-values are represented correctly in generated documentation (usnistgov/OSCAL#TBD)

NB - this feature is relied on most heavily in the SSP schema, but schema modularity (combining with or overriding declarations in other schema modules) *is* in scope and must be tested.

The good news is that the problem can probably be addressed at a single point, namely in the metaschema composition phase.

**Comment by wendellpiez** [comment]
**March 12 Update**

This work is happening in my repo: see #39.

**Comment by david-waltermire-nist** [comment]
For allowed values defined without a specific context, such as those on flags and field values, it is possible to use enumeration features in XSD and JSON schema type definition systems. We should focus on this low-hanging-fruit to add support to the XSLT and Java schema generation frameworks.

**Comment by wendellpiez** [comment]
This Issue was a "forget-me-not" written in 2019. It needs to be rewritten and closed. It encompasses all the below:

- Unit tests for `allowed-value` usage
- Implementation and testing against those tests (in any/all implementations)
- Documentation of the features

Note that `allowed-values` is only one of the constraint types to which this applies.
