### ISSUE TITLE
Website Search Feature Searches OSCAL Site on pages.nist.gov, Not Metaschema Site

### ISSUE THREAD

**Issue by aj-stein-nist** [usnistgov/metaschema#193]
# Describe the bug

I have tried obvious queries for generic terms of art, [like `Metaschema`](https://search.usa.gov/search?affiliate=oscal&utf8=%E2%9C%93&query=Metaschema) or [`managed objects`, which is a phrase explicitly lifted from the Metaschema landing page](https://search.usa.gov/search?affiliate=oscal&utf8=%E2%9C%93&query=managed+objects) and no matter what I try, it seems the USAGov Search facility on the Metaschema site only indexes and returns content from the OSCAL site, not this one.

# Who is the bug affecting?

Any developer trying to search for information about Metaschema by keyword on this [pages.nist.gov/metaschema]().

# What is affected by this bug?

The ability to search content with the native search feature without Google-dorking.

# When does this occur?

Consistently.

# How do we replicate the issue?

1. Visit the site.
1. Attempt to search for any unique concept of phrase on the Metaschema site.
1. Review results, all are from the OSCAL site, not the Metaschema site.

# Expected behavior (i.e. solution)

To search and see results specific to the Metaschema site.

# Other Comments

Not sure it is possible or intended with setting up a distinct affiliate code or site configuration with the current `oscal` affiliate code. Maybe there were reasons this was not done? If so, feel free to close.

**Comment by david-waltermire-nist** [comment]
This was addressed in commit [37ca9d0b8f723e2410431cd049171b7a251de48d](https://github.com/usnistgov/metaschema/commit/37ca9d0b8f723e2410431cd049171b7a251de48d).
