### ISSUE TITLE
Metaschema changes from #191

### ISSUE THREAD

**Issue by david-waltermire-nist** [usnistgov/metaschema#195]
# User Story:

As a user of the XSLT-based Metaschema toolchain, I want support for the latest Metaschema changes.

The following changes require updates to the XSLT-based toolchain.

- [x] XML data type schemas have been moved to `schema/xml`. These should be dynamically injected as part of XML schema generation.
   - [x] `metaschema.xsd` is the new metaschema XSD
   - [x] `metaschema-datatypes.xsd` contains all non-prose datatypes
   - [x] `metaschema-prose-base.xsd` contains all prose support types needed by line and multiline. These types are not duplicated in the two schemas below.
   - [x] `metaschema-markup-line.xsd` contains only the XML types for markup line
   - [x] `metaschema-markup-multiline.xsd` contains only the XML types for markup multiline
 - [x] JSON data type schema have been moved to `schema/json`. These should be dynamically injected as part of JSON schema generation.
   - [ ] `metaschema-datatypes.json` contain all JSON data types
- [x] Some data types have been renamed for better naming consistency. Both the old name and the new name should be honored in any implementation. old names should be mapped automatically to new names in the tool.
   - [x] nonNegativeInteger -> non-negative-integer
   - [x] positiveInteger -> positive-integer
   - [x] dateTime -> date-time
   - [x] base64Binary -> base64
   - [x] dateTime-with-timezone -> date-time-with-timezone
   - [x] email -> email-address
- [x] JSON value keys have changed to address #169. They are split between:
   - [x] `<json-value-key>flag-name</json-value-key>`
   - [x] `<json-value-key-flag flag-ref="flag-name"/>` **note the change in `flag-name` to `flag-ref`.
- [x] Add support for the [year-month-duration](https://github.com/usnistgov/metaschema-java/blob/main/metaschema-model-common/src/main/java/gov/nist/secauto/metaschema/model/common/datatype/adapter/YearMonthAdapter.java) and [day-time-duration](https://github.com/usnistgov/metaschema-java/blob/main/metaschema-model-common/src/main/java/gov/nist/secauto/metaschema/model/common/datatype/adapter/DayTimeAdapter.java) data types. #188
## Goals:

Update the XSLT-based tooling to address these changes.

## Dependencies:

None.

## Acceptance Criteria

- [ ] All [website](https://pages.nist.gov/metaschema) and readme documentation affected by the changes in this issue have been updated. Changes to the website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by wendellpiez** [comment]
See #214 and its working branch for updates. Remaining on this Issue:

- double check all line items have been addressed
- review datatypes - old datatypes are no longer supported: should we restore them?

**Comment by wendellpiez** [comment]
Noting on the second item - inasmuch as we do not expect to be using or even deploying these schemas, backward-compatibility with old datatypes shouldn't be an issue (they can use older schemas, or migrate).

This is ready for review -- PR #214

**Comment by wendellpiez** [comment]
@david-waltermire-nist apparently I have no permissions to check boxes but all the boxes above can be checked - everything here has been done and can be tested in the branch behind PR #214.
