### ISSUE TITLE
[EPIC] Create a programing language data API generator

### ISSUE THREAD

**Issue by david-waltermire-nist** [usnistgov/metaschema#20]
# User Story:

As a user of a Metaschema-based model, I need to be able to quickly build tooling that can load and save content valid to that model.

## Goals:

Create one or more tools that can generate a data API in one or more programing languages based on a model described by a Metaschema. Each language binding must be capable of loading/saving XML, JSON, and YAML content.

Languages to be supported include:
- [x] Java ([usnistgov/metaschema-java](https://github.com/usnistgov/metaschema-java/) and [usnistgov/liboscal-java](https://github.com/usnistgov/liboscal-java))
- [ ] Javascript/Typescript
- [ ] Python
- [ ] c/c++
- [ ] C#
- [ ] Rust
- [ ] Golang
- [ ] Ruby

**Comment by aj-stein-nist** [comment]
@david-waltermire-nist we pinned it to the repo as a novel way to solicit community interest and reporting around libraries they had made. It's still pinned on top of the issues list.

![image](https://user-images.githubusercontent.com/94922603/218806519-1bddaadf-271f-4dc6-9ab6-7209de68d25d.png)

So if we want to communicate that still, we might want to add work to update the website or some other mechanism, or remove it as the only pinned issue.
