### ISSUE TITLE
Docs adjustments needed - Metaschema object types

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/metaschema#211]
# Describe the bug

On the Metaschema Pages site, this page has a few small errors:  https://pages.nist.gov/metaschema/specification/mapping/

note:

- datatypes are called 'markup-line' and 'markup-multiline'
- 'markup-multiline' description is inaccurate
- field values, not only flags, can be assigned a type for lexical checking

# Who is the bug affecting?

Anyone who refers to this page

# Expected behavior (i.e. solution)

Let's update. All page contents should be reviewed for accuracy.

**Comment by aj-stein-nist** [comment]
Re @david-waltermire-nist we need to update the OSCAL docs, and back-propagate the changes back to this page as well.

**Comment by aj-stein-nist** [comment]
Are these issues with misaligned docs still the case, @wendellpiez? Should we tackle this sooner rather than later?
