### ISSUE TITLE
Upgrade GitHub CI/CD Workflows to Current Stable Version

### ISSUE THREAD

**Issue by aj-stein-nist** [usnistgov/metaschema#216]
# User Story:

As an OSCAL tool developer, in order to make sure CI/CD is properly developed and integrated in relevant OSCAL projects, I want the current version of GitHub Actions CI/CD workflows updated to current stable.

## Goals:

The NIST OSCAL Team will complete cleaning, deduplification, and misc improvements to the GitHub Actions in [usnistgov/OSCAL](https://github.com/usnistgov/OSCAL/) for improved maintenance, stability, and resiliency.

## Dependencies:

- [x] Completion of usnistgov/OSCAL#1223

## Acceptance Criteria

- [ ] All readme documentation affected by the changes in this issue have been updated.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by david-waltermire-nist** [comment]
@aj-stein-nist Is there something more to do here relating to this issue? It's not clear. Should I close this?

**Comment by aj-stein-nist** [comment]
> @aj-stein-nist Is there something more to do here relating to this issue? It's not clear. Should I close this?

I cannot recall and it does not seem that relevant anymore, so with that ...
