### ISSUE TITLE
Add Identifier Use Properties to Metaschema Schema for Model Use

### ISSUE THREAD

**Issue by aj-stein-nist** [usnistgov/metaschema#222]
# User Story:

As a NIST OSCAL developer, in order to [clearly define identifier information in a meaningful way](https://pages.nist.gov/OSCAL/concepts/identifier-use/) in model definitions in Metaschema and automate document generation from it, I would like these added to the schema as possible `prop`s.

## Goals:

This has come up several times, but in its latest iteration https://github.com/david-waltermire-nist/OSCAL/pull/49#pullrequestreview-1055727001. @aj-stein-nist volunteered to attempt this change to further that as part of ongoing work for usnistgov/OSCAL#1331 in usnistgov/OSCAL#1263.

## Dependencies:

{Describe any previous issues or related work that must be completed to start or complete this issue.}

## Acceptance Criteria

- [ ] All [website](https://pages.nist.gov/metaschema) and readme documentation affected by the changes in this issue have been updated. Changes to the website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

{The items above are general acceptance criteria for all User Stories. Please describe anything else that must be completed for this issue to be considered resolved.}

**Comment by aj-stein-nist** [comment]
I recommend we include this for a release before or latest as a part of `1.0.0` release.

**Comment by david-waltermire-nist** [comment]
Metaschema properties were implemented in a prior commit. Use of properties to support identifier use is an OSCAL issue. Closing.
