### ISSUE TITLE
XSD datatype glitch in XSLT M4 schema generator

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/metaschema#223]
# Describe the bug

For whatever reason, derived datatypes are not capturing their base types in the generated XSDs (XSLT M4 implementation, `develop` branch). For example, `dateTime-with-timezone` should be defined as a restriction on `dateTime`, but is coming through as a restriction on `string`.

# Who is the bug affecting?

Downstream users of the XSD who do not have correct data type bindings.

# What is affected by this bug?

Difficult to determine, but this has potential impacts on XSD-based applications.

# When does this occur?

Reliably on certain datatypes in OSCAL (that are derived by restriction).

# How do we replicate the issue?

Examine any generated schema.

# Expected behavior (i.e. solution)

Schemas should reflect the derivation of the type, not erase it.

**Comment by wendellpiez** [comment]
Current plan:

- [ ] expose this bug in a unit test over the dateTime-with-timezone example (plus cf #224)
- [ ] leave the regex in its current form but correct the data type derivation
  - [ ] showing this with the unit test

Then we have a start at #224 (exposing the regex issues).

**Comment by wendellpiez** [comment]
[datatypes-datetime-no-tz_metaschema.xml.txt](https://github.com/usnistgov/metaschema/files/9384746/datatypes-datetime-no-tz_metaschema.xml.txt)
[datatypes-datetime-no-tz_metaschema-xmlschema.xsd.txt](https://github.com/usnistgov/metaschema/files/9384747/datatypes-datetime-no-tz_metaschema-xmlschema.xsd.txt)

@david-waltermire-nist I wonder if you would look at these?

**Comment by wendellpiez** [comment]
PR #227 addresses this Issue.

**Comment by wendellpiez** [comment]
*Actually* - the bug found and repaired for #227 may not be this one, at least as described in this Issue (which was transcribed from a note). TBD.

**Comment by david-waltermire-nist** [comment]
@wendellpiez The specific error can be verified by validating the [OSCAL catalog XML schema](https://raw.githubusercontent.com/usnistgov/OSCAL/develop/xml/schema/oscal_catalog_schema.xsd).

**Comment by wendellpiez** [comment]
The schema generated from adjusted XSD comes up without errors, and the diff shows new structures (only).

Thanks @david-waltermire-nist for the reference point.
