### ISSUE TITLE
Support sequences of objects of different types

### ISSUE THREAD

**Issue by david-waltermire** [usnistgov/metaschema#228]
# User Story:

As a Metaschema model maintainer, I need a way to allow sequenced collections of objects of different types.

This could be accomplished using a syntax similar to the following.

```
<choice min-occurs="1" max-occurs="unbounded">
    <group-as name="tests" in-json="ARRAY"/>
    <discriminator in-json="object-type"/>
    <assembly ref="rule-condition">
        <use-name>condition</use-name>
        <discriminator-value>condition</discriminator-value>
    </assembly>
    <assembly ref="test-reference">
        <discriminator-value>test-reference</discriminator-value>
    </assembly>
    <field ref="testing-scenario-reference">
        <discriminator-value>testing-scenario</discriminator-value>
    </field>
</choice>
```

A JSON could look like the following.
```
{
    "tests": [
      {
        "object-type": "condition",
      },
      {
        "object-type": "test-reference"
      },
      {
        "object-type": "condition",
      },
      {
        "object-type": "testing-scenario"
      }
    ]
}
```

While the XML would look like:

```
<condition .../>
<test-reference .../>
<condition .../>
<testing-scenario-reference .../>
```

## Goals:

- [ ] define the Metaschema syntax for this
- [ ] create follow-on issues to implement this in the XSLT and Java codebases

## Dependencies:

None.

## Acceptance Criteria

- [ ] All [website](https://pages.nist.gov/metaschema) and readme documentation affected by the changes in this issue have been updated. Changes to the website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by wendellpiez** [comment]
I would very much welcome any ideas, concepts or leads on how to validate this in JSON and YAML, maybe whether JSON-LD or some similar extension provides a validation model especially one that is robust and well-liked.

FWIW in XML DTD or RNC syntax the mixed sequence pattern here is written as `(a | b | c)*` or `(a | b | c)+` whereas current Metaschema supports only `(a | b | c)` (a choice, but only one), `a+, b+` or `a*, b*` etc. (multiples, but not mixed).

One way to validate a mixed sequence is to cast all the `object-type` properties on children in sequence (array members in order) to a string, and match that against a regular expression representing (written as a cast from) the model. This is ugly but I have seen it work. Terrible error messages come back (not very useful even if you understand them). I am also skeptical that deploying such a test would be easily done in JSON Schema. Translating the model into bottom-up tests at the node level is a more attractive idea - is there a JSON Schema way to enforce a property value (here, `object-type`) be one of an enumeration, on any given array member (i.e. member of `tests`)? The metaschema constraint layer may also give us another place to intervene with testing, providing we get a parse.

FWIW this is much easier if we do *not* have to support `a*, (b | c | d)*, e*`, i.e. mixed sequences within ordered sequences (something that DTD, RNG and XSD all support for XML).

Suggest `#object-type` or some other prefixed name to keep clear of names of flags (arbitrarily-named properties defined by the metaschema) on these objects.
