### ISSUE TITLE
Constraint Has Its Own Unique Name or ID

### ISSUE THREAD

**Issue by aj-stein-nist** [usnistgov/metaschema#232]
# User Story:

As a NIST OSCAL developer, in order to consistently and easily identify a Metaschema constraint in any Metaschema model, I would like an identifier or name field to be allowed so I can uniquely define that constraint in that model.

## Goals:

- [x] Model and design an `@id` or `@name` field that allows unique reference of a constraint in a given model
- [x] Implement it in Metaschema core schema

Original rationale and goals can be found in [the comment](https://github.com/usnistgov/OSCAL/issues/1331#issuecomment-1213466130), leading to the creation of this issue.

## Dependencies:

N/A

## Acceptance Criteria

- [ ] All [website](https://pages.nist.gov/metaschema) and readme documentation affected by the changes in this issue have been updated. Changes to the website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

{The items above are general acceptance criteria for all User Stories. Please describe anything else that must be completed for this issue to be considered resolved.}

**Comment by aj-stein-nist** [comment]
Dave wants to consider the creation of a micro-format to build (and potentially automatically generate respective IDs for each of them) the constraints and insert them in. Discuss with Dave and rewrite the feature's user story, goals, and AC.

**Comment by aj-stein-nist** [comment]
Removing OSCAL work board per discussion with @david-waltermire-nist.

**Comment by david-waltermire-nist** [comment]
This has been [implemented](https://github.com/usnistgov/metaschema/blob/5f515396332fd34c8c1ff5d02013ae9ee0052e8d/schema/xml/metaschema.xsd#L548).
