### ISSUE TITLE
Update Metaschema Syntax Documentation to Refer to Token Types, Not IDs

### ISSUE THREAD

**Issue by aj-stein-nist** [usnistgov/metaschema#238]
# User Story:

As a NIST OSCAL developer, in order to properly understand JSON enhancement features, I would like to have clearer documentation about key, ID, and the appropriate Metaschema types.

## Goals:

- [x] Update the following section and additional relevant references on [the syntax page](https://pages.nist.gov/metaschema/specification/syntax/).

> To support this, flags used as addresses should be declared as type ID, providing "an extra layer of protection". On the JSON side, validating the uniqueness of these values (on same-named properties across document scope) remains TBD.

## Dependencies:

{Describe any previous issues or related work that must be completed to start or complete this issue.}

## Acceptance Criteria

- [ ] All [website](https://pages.nist.gov/metaschema) and readme documentation affected by the changes in this issue have been updated. Changes to the website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

{The items above are general acceptance criteria for all User Stories. Please describe anything else that must be completed for this issue to be considered resolved.}

**Comment by aj-stein-nist** [comment]
Per discussion with team reorganization, I will move this Metaschema issue off the NIST OSCAL workboard.

**Comment by aj-stein-nist** [comment]
I recommend we include this for a release before or latest as a part of `1.0.0` release.

**Comment by david-waltermire-nist** [comment]
Addressed by PR #329.
