### ISSUE TITLE
Documentation of Scopes?

### ISSUE THREAD

**Issue by aj-stein-nist** [usnistgov/metaschema#239]
# User Story:

As a NIST OSCAL developer, to better understand models and implement specification-conformant Metaschema parsing library, I would like explanation and examples of implementation processing around `@scope`s.

## Goals:

- [x] Explain scopes in terminology and/or syntax pages
- [x] Demonstrate through an example how `@scope` being `local` or `global` impacts processing of modules from `//import`s.

## Dependencies:

{Describe any previous issues or related work that must be completed to start or complete this issue.}

## Acceptance Criteria

- [ ] All [website](https://pages.nist.gov/metaschema) and readme documentation affected by the changes in this issue have been updated. Changes to the website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

{The items above are general acceptance criteria for all User Stories. Please describe anything else that must be completed for this issue to be considered resolved.}

**Comment by aj-stein-nist** [comment]
Per discussion with team reorganization, I will move this Metaschema issue off the NIST OSCAL workboard.

**Comment by david-waltermire-nist** [comment]
Addressed by PR #329.
