### ISSUE TITLE
Developer Onboarding Page: What problem is Metaschema solving?

### ISSUE THREAD

**Issue by aj-stein-nist** [usnistgov/metaschema#252]
# User Story:

As an OSCAL tool developer, to better understand why I should write parsers and language libraries reading Metaschema definitions and not OSCAL JSON/XML schemas, I want to know what problems Metaschema is solving. Once I know these problems, I want to know the estimated level of effort of parsing Metaschema versus directly parsing resultant JSON/XML schemas, the benefits, and downsides of this approach.

## Goals:

Establish an elevator pitch for new developers considering adoption of Metaschema parsing over OSCAL

## Dependencies:

N/A

## Acceptance Criteria

- [ ] All [website](https://pages.nist.gov/metaschema) and readme documentation affected by the changes in this issue have been updated. Changes to the website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

{The items above are general acceptance criteria for all User Stories. Please describe anything else that must be completed for this issue to be considered resolved.}

**Comment by isimluk** [comment]
Let me add a bit of color from a my perspective as an author of https://github.com/GoComply/metaschema : 

I wanted to create opensource OSCAL data model in golang. First thing I noticed is that there is a lot (!) of OSCAL models/entities. And I realised that I need to automate the model generation, there was no way I could write models manually. So, I wrote https://github.com/GoComply/metaschema to read OSCAL metaschema and to generate golang models (and parsers) for me.

If there were only few OSCAL entities, I wouldn't need to implement metaschema.

Hope this helps. :crossed_fingers:

**Comment by brandtkeller** [comment]
Follow-on from the above, my background is application development, particularly in Open Source. OSCAL at a high-level presents well understood value.

It's possible to hard-code a schema into(currently golang) data types and proceed with the core application logic - but as has been presented by others, there are more reliable and validatable processes to creation of these that would enable those working with a language to interface with OSCAL.

This currently looks to require learning and building upon metaschema - which at first glance is complex.

Personal goals are to help build the OSCAL ecosystem and bolster it with tooling - but paths for language support are either undocumented or do not exist. 

Recommendations for building OSCAL tools and language support would be appreciated. Understanding the nuance of building libraries for language support that stem from metaschema as opposed to the JSON schemas would also be appreciated.
