### ISSUE TITLE
Build Metaschema Level 1 Capabilities Tutorial

### ISSUE THREAD

**Issue by aj-stein-nist** [usnistgov/metaschema#260]
# User Story:

As a Metaschema-enabled tool developer, to know what is minimally required for a Level 1 Capability Metaschema library, I want a tutorial in one (or more languages) to walk through implementing those capabilities and what key characteristics of Metaschema syntax to do so.

## Goals:

Make tutorials to aid developers of Metaschema-enabled tools to boostrap in their language/runtime/library selection of choice and build MVP functionality for a Level 1 Capability Metaschema-enabled tool.

## Dependencies:

- [ ] usnistgov/metaschema#259

## Acceptance Criteria

- [ ] All [website](https://pages.nist.gov/metaschema) and readme documentation affected by the changes in this issue have been updated. Changes to the website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

{The items above are general acceptance criteria for all User Stories. Please describe anything else that must be completed for this issue to be considered resolved.}

**Comment by david-waltermire-nist** [comment]
We talked on the 12/2 Metaschema API call about creating single annotated example around a single or small set of Metaschema features to discuss on the 12/16 Metaschema API call. This is a way to start moving forward and to collect some initial feedback from the group.
