### ISSUE TITLE
Metaschema modeling docs corrections

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/metaschema#310]
### Discussed in https://github.com/usnistgov/metaschema/discussions/309

Note the below.

There could be other errors or opportunities for improvement on that page as well.

<div type='discussions-op-text'>

<sup>Originally posted by **nikitawootten-nist** February  1, 2023</sup>
Hi all, I'm looking over the "Metaschema Syntax" page under the heading "Metaschema modeling" (https://pages.nist.gov/metaschema/specification/syntax/#metaschema-modeling). **Is the following excerpt a typo**:

https://github.com/usnistgov/metaschema/blob/529ff85fd10985c850e420de2a0f33fd84fc3663/website/content/specification/syntax/_index.md?plain=1#L680

AFAIK `@required` **only applies to flags**? "Requirement" is to be handled in fields and assemblies using `@{min,max}-occurs`? The capability to represent `@required` is *not* present in metaschema-java: https://pages.nist.gov/metaschema-java/apidocs/gov/nist/secauto/metaschema/model/common/IFieldInstance.html

Feel free to convert this into an issue and I can volunteer to open a PR if this is indeed a typo :)</div>

**Comment by wendellpiez** [comment]
@nikitawootten-nist I see all kinds of issues with that page actually. What is this 'fields' it talks about? This may reflect a design that predates even our introduction of `@min-occurs` and `@max-occurs` to define cardinality. It says nothing about links. etc.

I haven't dug in to see how far back this goes.

But the problem is fixable: let me know. @david-waltermire-nist should I make a PR for this?

**Comment by david-waltermire-nist** [comment]
Addressed by PR #329.
