### ISSUE TITLE
Define and support a UUID data type.

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/metaschema#32]
# User Story:

We currently have no support for validating a UUID value as such. This necessitates a workaround -- 
 either defining a data point (expected to be a UUID) as a string, which permits spaces and characters not in UUIDs; or as XML NCName, which is a little better but also not right. Consequently, UUIDs are now being prefixed with `uuid-` simply to ensure validity, since NCName cannot begin with a digit, and a UUID can.

## Goals:

* Support a UUID data type with appropriate lexical constraints over UUIDs
* Revise models in OSCAL to take advantage of this datatype in document-level ID values or wherever UUIDs are called for.

The second of these items will be done in the OSCAL repo.

## Dependencies:

This work should be done under unit testing and requires unit tests.

## Acceptance Criteria

- [ ] All [website](https://pages.nist.gov/metaschema) and readme documentation affected by the changes in this issue have been updated. Changes to the website can be made in the docs/content directory of your branch. **Applies to Metaschema work**
- [ ] A Pull Request (PR) is submitted that fully addresses the first goal of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.
- [ ] An Issue has been created in the OSCAL repo to support the second goal, assuming it remains a goal.

{The items above are general acceptance criteria for all User Stories. Please describe anything else that must be completed for this issue to be considered resolved.}

**Comment by david-waltermire-nist** [comment]
PR #54 addressed this issue.
