### ISSUE TITLE
Remove any unwanted node tests from Metapath

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/metaschema#52]
# User Story:

As a subset of XPath, Metapath is much tighter, cleaner and well fitted to the data model defined by a Metaschema. But there are a couple of loose ends.

Four XPath node tests in particular may not be wanted: `processing-instruction()`, `comment()`, `text()` and `node()`. Metaschema has no types of nodes analogous to XDM processing instructions, comments or text nodes; and the catch-all `node()` node test is not necessary if we have nothing but elements and attributes (as representing assemblies, fields and flags in the XML) and we retain the `*` wildcard.

(`comment()` may already have been removed.)

## Goals:

- The EBNF that defines Metapath has been modified to exclude the unwanted node tests
- The Metapath parser XSLT has been regenerated from the new EBNF
- All implemented Metapath functionality, in schema and convertor generators, including Schematron generators, functions correctly with the new parser.

## Dependencies:

It is TBD how easy or practical it will be to remove these from Metapath; in particular, `processing-instruction()` may be tricky to remove since it can accept an argument.

## Acceptance Criteria

- [ ] All [website](https://pages.nist.gov/metaschema) and readme documentation affected by the changes in this issue have been updated. Changes to the website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

OR, an alternative to the above:
- [ ] We determine it is not practical, possible or a good idea to remove any or all of these.

**Comment by david-waltermire-nist** [comment]
There is an [ANTLR grammer for Metapath](https://github.com/usnistgov/metaschema-java/blob/main/metaschema-model-common/src/main/antlr4/metapath10.g4). It does not include these tests. We should update the XSLT-oriented grammar to be in sync with the ANTLR grammer. This should be the focus of this task.

**Comment by wendellpiez** [comment]
This Issue can be closed.

When we revisit Metapath in the XSLT Implementation we can do it with an entirely new technology (Invisible XML) and grammar.

Question: Should we publish a formal grammar for Metapath, making it easier for devs?

**Comment by david-waltermire-nist** [comment]
The ANTLR grammar doesn't include support for these types of tests.
