### ISSUE TITLE
Produce "prototype" XML documents from metaschemas for unit testing

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/metaschema#58]
# User Story:

For purposes of testing (transformations, processes, conversions) it is sometimes useful to have 'prototype' XML documents conforming to a schema, representing all elements (or an appropriate range of elements) in 'normal' arrangements, with Lorem Ipsum text or the equivalent.

For example, an AP (assessment plan) prototype document could be put through the bidirectional conversion to test the conversion process.

Such a prototype could be produced programmatically from a metaschema. A transformation that produced such a prototype could be integrated into a production pipeline to provide examples for testing, supplementary to real-world or handmade test instances.

```xml
<catalog uuid="00000000">
  <metadata>
    <title>title title title</title>
    <publication-date>[dummy date as a valid date string]</publication-date>
...
</catalog>
```

## Goals:

Produce a transformation that generated, for a metaschema, valid outputs, demonstrating a useful range of element usage, for testing. Optional elements should be represented. Where models show "choice", both choices (wherever possible) should be represented (in parallel structures).

Data type values e.g. dates etc. should be produced in correct lexical form.

Inline markup (`markup-line`) and "prose blocks" (`markup-multiline`) should show enough complex cases that the markdown conversion is effectively invoked as well, wherever these structures are permitted.

Such prototype documents might also be useful when it comes to testing validation of the enhanced constraints model, for generated tests (XSpec?) or as as scaffolding for unit tests maintained by hand.

## Dependencies:

Having completed this we need to determine to what extent to integrate such documents into testing and CI/CD, and make Issues appropriately as follow-ons.

## Acceptance Criteria

- [ ] All [website](https://pages.nist.gov/metaschema) and readme documentation affected by the changes in this issue have been updated. Changes to the website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by wendellpiez** [comment]
XSLTs that address *part* of the functional requirement set described here is available in the oscal-tools repo: https://github.com/usnistgov/oscal-tools/tree/main/xslt/generate

**Comment by david-waltermire-nist** [comment]
Not sure this is the ideal way to test metaschemas. It might be better to use specific constructed metaschema instances that test the specific functionality we need to test.

Closing this for now.
