### ISSUE TITLE
Scripting Metaschema productions in Typescript / node js

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/metaschema#62]
# User Story:

Eventually we will want to emulate current processes scripted under CI/CD (in build/scripts), except in Typescript / node js, to work with the OSCAL CI/CD and testing (usnistgov/OSCAL#699).

This runtime could call SAXON in Java to provide XSLT support, or it could potentially use Saxon-JS from within the Typescript itself.

(This is currently a placeholder issue for a task not on the critical path at time of writing.)

## Goals:

Emulate current scripting capabilities in node js using Typescript syntax.

(Specific goals / organization TBD.)

## Dependencies:

Metaschema processing under XSLT (M4) must be stable.

## Acceptance Criteria

- [ ] All [website](https://pages.nist.gov/metaschema) and readme documentation affected by the changes in this issue have been updated. Changes to the website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by wendellpiez** [comment]
Some preliminary wip is in this branch: https://github.com/wendellpiez/metaschema/tree/issue62-ts-scripting

**Comment by david-waltermire-nist** [comment]
This is being addressed in the [usnistgov/oscal-cli-nodejs](https://github.com/usnistgov/oscal-cli-nodejs) implementation, which was moved out of this repo.
