### ISSUE TITLE
Whitespace collapse on datatypes in XSD foils bi-directional conversion (Metaschema M3)

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/metaschema#67]
# Describe the bug

Probably related to the bug described in #66.

In the generated XSDs, a property `whiteSpace` is set to `collapse` on datatyped values. This provides whitespace normalization which (among other things) makes values valid to patterns that would otherwise be invalid due to whitespace. This was detected on a UUID value that passes XSD validation even when it has trailing space.

Since the conversion utility does not collapse whitespace, a value (with whitespace) that is not actually valid to the datatype's lexical pattern, appears in the result. This causes problems downstream, for example when the data is cast into JSON, where its schema shows it is invalid.

# Who is the bug affecting?

Edge cases with sloppy data in datatyped values - which makes it especially annoying since it only happens *sometimes*.

# What is affected by this bug?

Potentially anyone, especially anyone relying on bidirectional conversion.

# When does this occur?

In any datatype now marked with `<whiteSpace value='collapse'/>` in its definition.

*Note* however that for the `markup-line` datatype, which converts to Markdown, we may wish to provide whitespace normalization -- although the problem there might be the reverse, if whitespace that persists in XML mixed content, is stripped in Markdown. More testing is in order.

# How do we replicate the issue?

Try and validate a document with a datatype value (such as a UUID or boolean) with extra whitespace. It should be valid in XSD, but when converted to JSON, it won't be valid to the corresponding JSON Schema (which does not provide for collapsing).

# Expected behavior (i.e. solution)

Data with extraneous whitespace should not validate against datatypes whose patterns do not permit it, in XSD.

Bidirectional conversion of all data, including pathological cases, should work.

# Other Comments

This needs to be addressed in both Metaschema M3, and M4.

Also, unit tests for schema validation and data conversion should provide some edge cases of data invalid only due to whitespace anomalies (extra whitespace not permitted by the given pattern).

**Comment by david-waltermire-nist** [comment]
See #68. This will be fixed against the M4 implementation.
