### ISSUE TITLE
Whitespace collapse on datatypes in XSD foils bi-directional conversion (Metaschema M4)

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/metaschema#68]
# Describe the bug

The bug described in #67 probably also appears in Metaschema M4 implementation.

Appropriate unit tests should be migrated, and any fix must be made in the M4 development branch.

**Comment by david-waltermire-nist** [comment]
This may be fixed, but we need a unit test to verify it. We have also removed collapse in the datatypes (completed in #191). This is probably closable.
