### ISSUE TITLE
Redesign "local scoping" feature in Metaschema definitions

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/metaschema#84]
# User Story:

In response to the use case described in #76, we implemented `scope='local'` on definitions in a Metaschema module to provide for (only) references in the same module to reference a definition; it works by expanding all such definitions in the composition phase.

This is not ideal as indeed we would like these type definitions at the *top level* (not inline) in XSD and JSON Schemas, while also limiting its scope of application (where it is invoked). Also, the current implementation will blow up on top-level 'local' definitions that call themselves recursively, either directly or indirectly -- and this is a feature we probably want.

## Goals:

Let's redesign the `scope='local'` feature of Metaschema modules so that they produce type definitions at the top level of the resulting schema artifacts, while their names/identifiers are disambiguated to prevent them from calling one another. Maybe rename it `scope='module'`?

## Dependencies:

This redesign should be reflected in unit tests demonstrating the necessary functionality and exception handling.

## Acceptance Criteria

- [ ] All [website](https://pages.nist.gov/metaschema) and readme documentation affected by the changes in this issue have been updated. Changes to the website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

{The items above are general acceptance criteria for all User Stories. Please describe anything else that must be completed for this issue to be considered resolved.}

**Comment by wendellpiez** [comment]
A new rule has been introduced to Metaschema composition: instead of being rewritten as an inline definition (broken) as in the old implementation, a definition marked `scope='local'` is left at the top level, but renamed with a prefix indicating its module of origin.

Both it, and the references (in the same module) that point to it, are also provided with `use-name` to carry the original name.

Since this happens in composition, both JSON Schema and XSD downstream inherit the scope names - so this might also help with disambiguating names across schema boundaries in the XSD production.

NB: with this change, documentation may break; in any case a new policy with prevalent use of `use-name` in the compiled metaschemas suggest that documentation production must be stress tested - see #84 #104 #105 #113.

**Comment by david-waltermire-nist** [comment]
Resolved by PR #116.
