### ISSUE TITLE
Model map enhancement: links to local definitions

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/metaschema#94]
# User Story:

As currently deployed, the model maps (XML and JSON) contain links from the respective models into appropriate documentation, but only for global definitions, not for assemblies or fields declared locally, or for flags in general.

This is because targets do not appear one for one in the maps or docs. A given local declaration will appear in a a map (and in the schema docs) as many times as it appears within the context of use of its globally defined ancestor, which could be many multiples (e.g., children of `part`).

An appropriate ID assignment can however be made deterministically using XSLT, for example with a tunnel parameter to trace the invocation context of (the appearance of) a local definition though the template stack from top to bottom.

## Goals:

Extend the production of model maps (XML and JSON) so that links work from any/all represented structures into analogous positions in the documentation, including from structures defined locally in their respective Metaschemas, not only globally.

## Dependencies:

None, although other Issues also address model maps and could be bundled: #91 #92.

## Acceptance Criteria

- [ ] All [website](https://pages.nist.gov/metaschema) and readme documentation affected by the changes in this issue have been updated. Changes to the website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by aj-stein-nist** [comment]
This work was completed with previous PRs in other sprints. Outstanding higher-level work around this issue can continue to be tracked in usnistgov/metaschema#120.
